api-football:
  sync:
    league-seasons:
      enabled: false
      run-on-startup: false
    teams:
      enabled: false
      run-on-startup: false
    standings:
      enabled: false
      run-on-startup: false
      local-finished-update-enabled: false
      local-live-update-enabled: false
      local-live-impact-ttl-hours: 6
    fixtures:
      enabled: false
      run-on-startup: false
    fixture-details:
      enabled: false
      run-on-startup: false
      chunk-size: 10
    players:
      profile-fallback-enabled: false
      registered:
        enabled: false
        run-on-startup: false
    injuries:
      enabled: false
      run-on-startup: false

live:
  sync:
    enabled: false
