spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
  # Kafka
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: soccer-streaming-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"

  # DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}