api-football:
  sync:
    teams:
      enabled: false
      run-on-startup: false
    standings:
      enabled: false
      run-on-startup: false
      local-finished-update-enabled: false
      local-live-update-enabled: false
      local-live-impact-ttl-hours: 6
    fixtures:
      enabled: false
      run-on-startup: false
    fixture-events:
      enabled: false
      test-runner-enabled: false
    fixture-lineups:
      enabled: false
      run-on-startup: false
    fixture-player-stats:
      enabled: false
      run-on-startup: false
    fixture-statistics:
      enabled: false
      run-on-startup: false
    players:
      profile-fallback-enabled: false
      squads:
        enabled: false
        test-runner-enabled: false
    injuries:
      enabled: false
      run-on-startup: false

live:
  sync:
    enabled: false
