input {
  file {
    id => "match-vault-application-json"
    path => ["/var/log/match-vault/application.json"]
    mode => "tail"
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/match-vault-application.sincedb"
    codec => json {
      ecs_compatibility => "v8"
    }
  }
}

output {
  elasticsearch {
    id => "match-vault-elasticsearch"
    hosts => ["http://elasticsearch:9200"]
    index => "match-vault-logs-%{+yyyy.MM.dd}"
  }
}
